In [1]:
import numpy as np
print(np.array([1,2,3])) #one dimensional aaray np.array([list])
print(np.array([[1,2,3],[4,5,6]])) #2 dimensional array

[1 2 3]
[[1 2 3]
 [4 5 6]]


# basic attributes 

In [2]:
#array_name.ndim give dimension check out no paranthesis
aray=np.array([[1,2,3],[4,5,6]])#all list shoul have same length
print(aray.ndim) 
print(aray.dtype)
type(aray)
print(aray.shape)
print(aray.size) #total no. of elements
b=aray.reshape(3,2) #reshape..changing nom of rows and columns
print(b)
#indexing
print(aray[0,0])
print(b.max(
)) #maximum
print(b.sum()) #add
print(aray.sum(axis=0))
print(aray.sum(axis=1))
print(np.sqrt(aray)) #square root..carefully obsrve
print(np.std(aray)) #standard deviation
print(np.mean(aray))
print(aray>2) #since it has given boolean lsit,we can acces other elemnts for true or false case fr operation #not happens
#in list onlu in array
print(np.exp(aray))
aray.T #TRANSPOSE OF ARAY MATRIX

2
int32
(2, 3)
6
[[1 2]
 [3 4]
 [5 6]]
1
6
21
[5 7 9]
[ 6 15]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
1.707825127659933
3.5
[[False False  True]
 [ True  True  True]]
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [3]:
a=np.linspace(1,4,6) #placing 6 numbers between 1-4
print(a)

[1.  1.6 2.2 2.8 3.4 4. ]


In [23]:
c=[2,5,7]
print(max(c))#maximum in list
print(sum(c))
#addition of two list gives cancatenatin while array gives addition elementwise
c1=np.array([2,4,7])
print(np.max(c1))
print(c1.max())
print(max(c)) #same with sum min al=nd others too



7
14
7
7
7


# copy method 

In [24]:
import numpy as np
abc= np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
bcd= abc[:2, 1:3]
print(bcd)
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(abc[0, 1])   # Prints "2"
bcd[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(abc[0, 1])   # Prints "77"
#for avoiding this,copy method works
bcd_copy=abc[:2,1:3].copy()
bcd_copy[0,0]=88 #now abc wont change
print(abc[0,1])



[[2 3]
 [6 7]]
2
77
77


# array indexing

In [25]:
#to remove above problem another type of indexing ..integer array indexing
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [26]:
#boolean indexing
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]],dtype=float) #second argument we can add data types

bool_idx = (a > 2)  
print(bool_idx)
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3. 4. 5. 6.]
[3. 4. 5. 6.]


In [27]:
#addition of two matrix #np.add(x,y) #np.substract(x,y) #np.multiply(x,y) #division too !!!!!!!!!!!
#matrix multiplication ??     np.dot(x,y) or #x.dot(y)
#transpose of a marix ??      array_name.T 

# array creation,varoius ways

In [28]:
#CREATING LONG ARRAYS
#A 15 LENGTH INTEGER ARRAY FILLED WITH ZERO
a=np.zeros(10,dtype=int)
print(a)
b=np.ones((3,5),dtype=int) #3*5 matrix filled with 1
print(b)
c=np.full((3,5),3,dtype=int) #3*5 matrix filled with 3
print(c)
#create AN array filled 0,2,4....upto 20
d=np.arange(0,20,2)
print(d)
##ceate 3*3 array of random values
e=np.random.random((3,3)) #double braces
print(e)
#create 3*3 array of mean 1 and standard deviation 2
f=np.random.normal(1,2,(3,3))
print(f)
#create 3,3 integer array in the interval 0,10
g=np.random.randint(0,10,(3,3))
print(g)
#identity matrix
h=np.eye(3)
print(h)
#creating empty 
np.empty(3)   #good practice to create empty list

[0 0 0 0 0 0 0 0 0 0]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]
[ 0  2  4  6  8 10 12 14 16 18]
[[0.7597763  0.74674996 0.29676172]
 [0.74594009 0.56068902 0.47294521]
 [0.33752398 0.83135358 0.09757621]]
[[-0.18899463 -2.55792792 -1.11243734]
 [ 1.70765898  0.5415824  -0.49226984]
 [ 1.79285825  0.01076968  1.65018082]]
[[3 5 2]
 [2 3 0]
 [2 2 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([1., 1., 1.])

# concatenation of array

In [29]:
x=np.array([1,2,3])
print(x.ndim)
y=np.array([4,5,6])
np.concatenate([x,y]) #can do for more than two arrays
 

1


array([1, 2, 3, 4, 5, 6])

In [30]:
print(np.vstack([y,x]))
print(np.hstack([x,y]))

[[4 5 6]
 [1 2 3]]
[1 2 3 4 5 6]


In [31]:
grid = np.array([[1, 2, 3],[4, 5, 6]])
grid1=np.array([[4,6,7],[9,10,11]])
print(np.concatenate([grid,grid1],axis=1)) #no. of rows remain same
print(np.concatenate([grid,grid1],axis=0)) #no. of column remains same
print(np.vstack([grid,grid1])) #vstack is similiar to concatenation along axis=0 #hstack is similiar to axis along 1

[[ 1  2  3  4  6  7]
 [ 4  5  6  9 10 11]]
[[ 1  2  3]
 [ 4  5  6]
 [ 4  6  7]
 [ 9 10 11]]
[[ 1  2  3]
 [ 4  5  6]
 [ 4  6  7]
 [ 9 10 11]]


# splitting of arrays 

In [32]:
x=[1,2,3,4,5,6,7,8] 
x1,x2,x3=np.split(x,[3,5]) #3 and 5 are splitting point ,,index of x
print(x1,x2,x3)

[1 2 3] [4 5] [6 7 8]


# computation through vectorisation and numpy ufuncs

In [33]:
x=np.array([-2,3,4,5]) 
print(1/x)
print(f"square of array is {x**2}.")
print(-(2*(x+5))**2) #whatever arithmetic operation you can used!!!!   cool
#although these arithmatic operation have numby built in function
print(np.abs(x)) #absolute value,also work if complex no, are there

[-0.5         0.33333333  0.25        0.2       ]
square of array is [ 4  9 16 25].
[ -36 -256 -324 -400]
[2 3 4 5]


In [34]:
print(np.pi) #accessing value of pi
print(np.sin(np.pi)) #similarly sin,cos,tan also there

3.141592653589793
1.2246467991473532e-16


# rules of broadcasting